export type EmojiCategoryId =
  | "frequent"
  | "smileys"
  | "animals"
  | "food"
  | "activity"
  | "travel"
  | "objects"
  | "symbols"
  | "flags";

export type MappedEmojiCategoryId = Exclude<EmojiCategoryId, "frequent">;

export type EmojiCategory = {
  id: EmojiCategoryId;
  labelKey: string;
  icon: string;
};

export type EmojiSearchLocale = "en" | "ru";

export const EMOJI_COLUMNS = 8;
export const EMOJI_CELL_SIZE = 40;
export const EMOJI_GRID_GAP = 6;
export const INITIAL_EMOJI_BATCH = EMOJI_COLUMNS * 5;
export const EMOJI_BATCH_STEP = EMOJI_COLUMNS * 4;

export const APPLE_EMOJI_CDN_BASE =
  "https://cdn.jsdelivr.net/gh/zhdsmy/apple-emoji@ios-18.4/png/160";

export const EMOJI_COMPONENT_SLUGS = new Set([
  "light-skin-tone",
  "medium-light-skin-tone",
  "medium-skin-tone",
  "medium-dark-skin-tone",
  "dark-skin-tone",
  "red-hair",
  "curly-hair",
  "white-hair",
  "bald",
]);

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  { id: "frequent", labelKey: "categories.frequent", icon: "❤️" },
  { id: "smileys", labelKey: "categories.smileys", icon: "🙂" },
  { id: "animals", labelKey: "categories.animals", icon: "🐻" },
  { id: "food", labelKey: "categories.food", icon: "🍔" },
  { id: "activity", labelKey: "categories.activity", icon: "⚽" },
  { id: "travel", labelKey: "categories.travel", icon: "✈️" },
  { id: "objects", labelKey: "categories.objects", icon: "💡" },
  { id: "symbols", labelKey: "categories.symbols", icon: "💯" },
  { id: "flags", labelKey: "categories.flags", icon: "🏳️" },
];

export const ORDERED_MAPPED_EMOJI_CATEGORIES: MappedEmojiCategoryId[] = [
  "smileys",
  "animals",
  "food",
  "activity",
  "travel",
  "objects",
  "symbols",
];

export const CATEGORY_SEARCH_TERMS: Record<
  EmojiSearchLocale,
  Record<MappedEmojiCategoryId, string[]>
> = {
  en: {
    smileys: ["smile", "smiley", "emotion", "face", "people", "person"],
    animals: ["animal", "nature", "pet", "bird", "flower", "tree"],
    food: ["food", "drink", "meal", "snack", "dessert"],
    activity: ["activity", "sport", "game", "music", "party"],
    travel: ["travel", "transport", "vehicle", "trip", "flight"],
    objects: ["object", "tool", "device", "tech", "thing"],
    symbols: ["symbol", "sign", "arrow", "button", "mark"],
    flags: ["flag", "country", "nation", "state"],
  },
  ru: {
    smileys: [
      "смайл",
      "смайлик",
      "улыбка",
      "эмоция",
      "лицо",
      "люди",
      "человек",
    ],
    animals: ["животное", "природа", "зверь", "цветок", "дерево"],
    food: ["еда", "напиток", "кушать", "вкусно"],
    activity: ["спорт", "активность", "игра", "музыка", "праздник"],
    travel: ["путешествие", "транспорт", "поездка", "машина", "самолет"],
    objects: ["предмет", "вещь", "инструмент", "техника"],
    symbols: ["символ", "знак", "стрелка", "кнопка"],
    flags: ["флаг", "страна", "государство"],
  },
};

export const TOKEN_SEARCH_ALIASES: Record<
  EmojiSearchLocale,
  Record<string, string[]>
> = {
  en: {
    airplane: ["plane", "aircraft", "jet"],
    automobile: ["car", "auto"],
    car: ["auto", "automobile"],
    cellphone: ["phone", "mobile", "smartphone"],
    grin: ["smile"],
    grinning: ["smile"],
    heart: ["love"],
    house: ["home"],
    laptop: ["computer"],
    loudly: ["loud"],
    mobile: ["phone", "smartphone"],
    thumbs: ["like", "approval"],
    trash: ["delete", "remove"],
  },
  ru: {
    alien: ["инопланетянин"],
    airplane: ["самолет"],
    angry: ["злой", "злость"],
    animal: ["животное", "зверь"],
    baby: ["ребенок", "малыш"],
    ball: ["мяч"],
    beach: ["пляж"],
    bear: ["медведь"],
    beer: ["пиво"],
    bird: ["птица"],
    blue: ["синий"],
    boat: ["лодка"],
    book: ["книга"],
    boy: ["мальчик"],
    bread: ["хлеб"],
    broken: ["разбитый"],
    building: ["здание"],
    burger: ["бургер"],
    bus: ["автобус"],
    button: ["кнопка"],
    cake: ["торт"],
    camera: ["камера"],
    candy: ["конфета"],
    car: ["машина", "авто"],
    cat: ["кот", "кошка"],
    chair: ["стул"],
    child: ["ребенок"],
    chocolate: ["шоколад"],
    circle: ["круг"],
    city: ["город"],
    clap: ["аплодисменты"],
    clock: ["часы"],
    cloud: ["облако"],
    coffee: ["кофе"],
    computer: ["компьютер"],
    cookie: ["печенье"],
    couple: ["пара"],
    cross: ["крест"],
    cry: ["плач"],
    crying: ["плач", "слезы"],
    dance: ["танец"],
    devil: ["дьявол"],
    dog: ["собака", "пес"],
    drink: ["напиток"],
    earth: ["земля"],
    emotion: ["эмоция"],
    exclamation: ["восклицание"],
    eye: ["глаз"],
    eyes: ["глаза"],
    face: ["лицо", "смайл", "смайлик"],
    family: ["семья"],
    finger: ["палец"],
    fire: ["огонь"],
    fish: ["рыба"],
    flag: ["флаг"],
    flower: ["цветок"],
    food: ["еда"],
    football: ["футбол"],
    fox: ["лиса"],
    frog: ["лягушка"],
    fruit: ["фрукт"],
    gift: ["подарок"],
    girl: ["девочка"],
    grinning: ["улыбка", "радость"],
    guitar: ["гитара"],
    hand: ["рука"],
    hands: ["руки"],
    happy: ["счастье", "радость"],
    heart: ["сердце", "любовь", "сердечко"],
    hotel: ["отель"],
    house: ["дом"],
    joy: ["радость", "смех"],
    key: ["ключ"],
    kiss: ["поцелуй"],
    kissing: ["поцелуй"],
    laptop: ["ноутбук"],
    laugh: ["смех"],
    laughing: ["смех", "ржу"],
    leaf: ["лист"],
    letter: ["буква"],
    light: ["свет"],
    lion: ["лев"],
    lock: ["замок"],
    loudly: ["громко"],
    mail: ["почта"],
    man: ["мужчина", "парень"],
    map: ["карта"],
    medal: ["медаль"],
    microphone: ["микрофон"],
    mind: ["разум", "мозг"],
    monkey: ["обезьяна"],
    money: ["деньги"],
    moon: ["луна"],
    mountain: ["гора"],
    mouth: ["рот"],
    movie: ["фильм"],
    music: ["музыка"],
    nose: ["нос"],
    number: ["число"],
    object: ["предмет"],
    ocean: ["океан"],
    package: ["посылка"],
    paper: ["бумага"],
    party: ["праздник", "вечеринка"],
    people: ["люди"],
    person: ["человек"],
    phone: ["телефон"],
    pizza: ["пицца"],
    plant: ["растение"],
    poop: ["какашка"],
    question: ["вопрос"],
    rain: ["дождь"],
    rage: ["ярость"],
    red: ["красный"],
    robot: ["робот"],
    road: ["дорога"],
    sad: ["грусть", "грустный"],
    screaming: ["крик"],
    ship: ["корабль"],
    shocked: ["шок"],
    sign: ["знак"],
    skull: ["череп"],
    sleep: ["сон"],
    sleepy: ["сонный", "сон"],
    smile: ["улыбка"],
    smiling: ["улыбка", "улыбается"],
    snow: ["снег"],
    sport: ["спорт"],
    square: ["квадрат"],
    star: ["звезда"],
    sweat: ["пот"],
    symbol: ["символ"],
    tea: ["чай"],
    tears: ["слезы"],
    tennis: ["теннис"],
    thumb: ["палец"],
    thumbs: ["палец", "лайк"],
    ticket: ["билет"],
    tiger: ["тигр"],
    tool: ["инструмент"],
    tongue: ["язык"],
    train: ["поезд"],
    travel: ["путешествие"],
    tree: ["дерево"],
    trophy: ["кубок"],
    up: ["вверх"],
    vegetable: ["овощ"],
    warning: ["предупреждение"],
    weapon: ["оружие"],
    whale: ["кит"],
    wine: ["вино"],
    woman: ["женщина", "девушка"],
  },
};

export const CATEGORY_KEYWORDS: Record<MappedEmojiCategoryId, string[]> = {
  smileys: [
    "teacher",
    "student",
    "judge",
    "farmer",
    "cook",
    "mechanic",
    "factory worker",
    "office worker",
    "technologist",
    "scientist",
    "artist",
    "singer",
    "pilot",
    "astronaut",
    "firefighter",
    "police officer",
    "police",
    "detective",
    "guard",
    "ninja",
    "superhero",
    "supervillain",
    "mage",
    "elf",
    "vampire",
    "zombie",
    "genie",
    "merperson",
    "mermaid",
    "merman",
    "prince",
    "princess",
    "pregnant",
    "breastfeeding",
    "bowing",
    "tipping hand",
    "raising hand",
    "facepalming",
    "shrugging",
    "health worker",
    "construction worker",
    "person with veil",
    "person in tuxedo",
    "face",
    "smile",
    "grin",
    "wink",
    "laugh",
    "cry",
    "emotion",
    "heart",
    "love",
    "kiss",
    "person",
    "people",
    "woman",
    "man",
    "baby",
    "adult",
    "child",
    "hand",
    "hands",
    "finger",
    "fingers",
    "eye",
    "eyes",
    "mouth",
    "nose",
    "family",
    "couple",
    "girl",
    "boy",
    "brain",
    "tongue",
    "ear",
  ],
  animals: [
    "animal",
    "animals",
    "dog",
    "cat",
    "bird",
    "chick",
    "chicken",
    "rooster",
    "hen",
    "duck",
    "eagle",
    "owl",
    "penguin",
    "dove",
    "flamingo",
    "parrot",
    "peacock",
    "swan",
    "turkey",
    "fish",
    "dolphin",
    "shark",
    "octopus",
    "shrimp",
    "seal",
    "whale",
    "monkey",
    "bear",
    "lion",
    "tiger",
    "wolf",
    "fox",
    "pig",
    "boar",
    "cow",
    "ox",
    "buffalo",
    "bison",
    "horse",
    "unicorn",
    "zebra",
    "deer",
    "camel",
    "llama",
    "giraffe",
    "elephant",
    "mammoth",
    "rhinoceros",
    "hippopotamus",
    "mouse",
    "hamster",
    "rabbit",
    "beaver",
    "otter",
    "chipmunk",
    "hedgehog",
    "raccoon",
    "skunk",
    "kangaroo",
    "badger",
    "paw",
    "frog",
    "crocodile",
    "turtle",
    "lizard",
    "snake",
    "dragon",
    "dinosaur",
    "sauropod",
    "rex",
    "bug",
    "ant",
    "bee",
    "honeybee",
    "butterfly",
    "snail",
    "beetle",
    "lady",
    "cricket",
    "cockroach",
    "spider",
    "scorpion",
    "mosquito",
    "fly",
    "worm",
    "nature",
    "flower",
    "blossom",
    "bouquet",
    "tree",
    "leaf",
    "plant",
    "herb",
    "cactus",
    "mushroom",
    "coral",
    "sun",
    "moon",
    "star",
    "fire",
    "cloud",
    "rain",
    "snow",
    "snowman",
    "earth",
    "mountain",
    "ocean",
  ],
  food: [
    "food",
    "drink",
    "fruit",
    "vegetable",
    "meal",
    "bread",
    "pizza",
    "burger",
    "coffee",
    "tea",
    "beer",
    "wine",
    "cocktail",
    "cake",
    "cookie",
    "chocolate",
    "candy",
    "ice cream",
  ],
  activity: [
    "sport",
    "ball",
    "game",
    "golf",
    "football",
    "basketball",
    "tennis",
    "medal",
    "trophy",
    "music",
    "guitar",
    "microphone",
    "movie",
    "ticket",
    "party",
    "dance",
    "clap",
    "event",
  ],
  travel: [
    "car",
    "taxi",
    "truck",
    "wheelchair",
    "tractor",
    "bike",
    "bicycle",
    "motorcycle",
    "scooter",
    "bus",
    "train",
    "tram",
    "metro",
    "railway",
    "airplane",
    "rocket",
    "helicopter",
    "ship",
    "boat",
    "travel",
    "transport",
    "road",
    "map",
    "building",
    "house",
    "hotel",
    "city",
    "place",
    "beach",
    "mountain",
    "camping",
    "tent",
    "statue",
  ],
  objects: [
    "phone",
    "computer",
    "laptop",
    "keyboard",
    "printer",
    "battery",
    "camera",
    "light",
    "tool",
    "key",
    "lock",
    "book",
    "money",
    "gift",
    "package",
    "weapon",
    "clock",
    "mail",
    "paper",
    "chair",
    "glass",
    "object",
    "bulb",
    "flashlight",
    "magnet",
    "pill",
    "microphone",
    "headphone",
    "radio",
    "gem",
    "crown",
    "ring",
    "briefcase",
  ],
  symbols: [
    "arrow",
    "sign",
    "symbol",
    "mark",
    "button",
    "number",
    "letter",
    "circle",
    "square",
    "cross",
    "exclamation",
    "question",
    "warning",
    "heart",
    "star",
    "zodiac",
    "currency",
    "plus",
    "minus",
    "multiply",
    "divide",
    "dot",
  ],
  flags: ["flag"],
};

export const FLAG_REGION_ALIASES: Partial<Record<string, string[]>> = {
  AE: ["оаэ", "uae"],
  CZ: ["чехия", "czech republic"],
  GB: ["uk", "britain", "great britain", "великобритания", "британия"],
  KP: ["north korea", "северная корея"],
  KR: ["south korea", "южная корея"],
  RU: ["рф", "российская федерация"],
  TR: ["turkiye", "турция"],
  US: ["usa", "сша", "america", "америка"],
};

export const EMOJI_SEARCH_LOCALES: EmojiSearchLocale[] = ["en", "ru"];

export const FREQUENT_EMOJIS = [
  "😂",
  "😘",
  "❤️",
  "😍",
  "😊",
  "😁",
  "👍",
  "😉",
  "🥲",
  "😭",
  "🔥",
  "🤔",
  "😎",
  "🥳",
  "🙏",
  "🤝",
  "😮",
  "😴",
  "🤯",
  "🤩",
] as const;
