export const CHAT_QUERY_SCOPE = "chat";

export const CHAT_MESSAGES_PAGE_SIZE = 200;
export const CHAT_MESSAGES_INITIAL_OFFSET = 0;

export const CHAT_REALTIME_RECONNECT_BASE_DELAY_MS = 1_000;
export const CHAT_REALTIME_RECONNECT_MAX_DELAY_MS = 5_000;
