/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * orisign API
 * HTTP gateway для сервисов orisign.

Аутентификация:
- `Authorization: Bearer <accessToken>` для защищенных endpoint'ов.
- `refreshToken` хранится в HttpOnly cookie и используется в `POST /auth/refresh`.

Ограничения:
- Глобальный rate limit: 5 запросов / 60 секунд.
- Для `POST /auth/otp/send`: 1 запрос / 30 секунд.
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type AccountResponseDtoRole = typeof AccountResponseDtoRole[keyof typeof AccountResponseDtoRole];


export const AccountResponseDtoRole = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_MINUS_1: -1,
} as const;

export interface AccountResponseDto {
  id: string;
  phone: string;
  /** @nullable */
  email: string | null;
  isPhoneVerified: boolean;
  isEmailVerified: boolean;
  role: AccountResponseDtoRole;
}

export interface InitEmailChangeRequestDto {
  /** Новый email для привязки */
  email: string;
}

export interface ChangeResponseDto {
  ok: boolean;
  challengeId?: string;
}

export interface ConfirmEmailChangeRequestDto {
  /** Challenge ID, полученный при инициации смены email */
  challengeId: string;
  /** Email, который подтверждается */
  email: string;
  /**
   * Код подтверждения
   * @minLength 6
   * @maxLength 6
   */
  code: string;
}

export interface InitPhoneChangeRequestDto {
  /** Новый номер телефона */
  phone: string;
}

export interface ConfirmPhoneChangeRequestDto {
  /** Challenge ID, полученный при инициации смены телефона */
  challengeId: string;
  /** Новый номер телефона */
  phone: string;
  /**
   * Код подтверждения
   * @minLength 6
   * @maxLength 6
   */
  code: string;
}

export interface SendOtpRequest {
  /** Номер телефона в международном формате (E.164 или без +) */
  phone: string;
  /** Уникальный идентификатор устройства клиента */
  deviceId: string;
}

export interface SendOtpResponseDto {
  ok: boolean;
  /** Одноразовый challenge для подтверждения OTP */
  challengeId: string;
}

export interface VerifyOtpRequest {
  /** Номер телефона, на который был отправлен OTP-код */
  phone: string;
  /**
   * Одноразовый 6-значный OTP-код
   * @minLength 6
   * @maxLength 6
   */
  code: string;
  /** Challenge ID, полученный на шаге отправки OTP */
  challengeId: string;
  /** Уникальный идентификатор устройства клиента */
  deviceId: string;
}

export interface AccessTokenResponseDto {
  /** JWT access token для Authorization Bearer */
  accessToken: string;
}

export interface ListSessionRequest {
  /** Идентификатор текущего устройства клиента */
  deviceId: string;
}

export interface SessionResponseDto {
  /** ID сессии */
  id: string;
  /** Идентификатор устройства */
  deviceId: string;
  /** User-Agent клиента */
  userAgent: string;
  /** IP-адрес клиента */
  ip: string;
  /** Unix timestamp создания сессии */
  createdAt: number;
  /** Unix timestamp последней активности */
  lastSeenAt: number;
  /** Текущая ли это сессия для вызывающего устройства */
  current: boolean;
}

export interface ListSessionsResponseDto {
  /** Список активных сессий пользователя */
  sessions: SessionResponseDto[];
}

export interface OkResponseDto {
  /** Признак успешного выполнения операции */
  ok: boolean;
}

export interface RevokeSessionRequestDto {
  /** ID сессии для завершения */
  id: string;
}

export interface GetUserRequestDto {
  /** ID пользователя */
  id?: string;
  /** Username пользователя */
  username?: string;
}

export interface CreateUserRequestDto {
  /** ID пользователя (обычно равен accountId из auth-service) */
  id: string;
}

export interface PatchUserRequestDto {
  /** Новый username */
  username?: string;
  /** Имя */
  firstName?: string;
  /** Фамилия */
  lastName?: string;
  /** Ссылки на аватары пользователя */
  avatars?: string[];
  /** Дата рождения в ISO-формате */
  birthDate?: string;
}

export interface PatchPrivacyRequestDto {
  /**
   * @minimum 0
   * @maximum 3
   */
  phone?: number;
  /**
   * @minimum 0
   * @maximum 3
   */
  lastSeenTime?: number;
  /**
   * @minimum 0
   * @maximum 3
   */
  photo?: number;
  /**
   * @minimum 0
   * @maximum 3
   */
  bio?: number;
  /**
   * @minimum 0
   * @maximum 3
   */
  call?: number;
  /**
   * @minimum 0
   * @maximum 3
   */
  reply?: number;
  /**
   * @minimum 0
   * @maximum 3
   */
  invite?: number;
  /**
   * @minimum 0
   * @maximum 3
   */
  mediaMessage?: number;
  /**
   * @minimum 0
   * @maximum 3
   */
  message?: number;
  /**
   * @minimum 0
   * @maximum 3
   */
  birthDate?: number;
}

export interface DeleteAvatarRequestDto {
  /** S3 object key avatar file */
  key: string;
}

export type UsersControllerAddAvatarBody = {
  file: Blob;
};

export const getOrisignAPI = (axiosInstance: AxiosInstance = axios) => {
/**
 * Возвращает данные аккаунта текущего авторизованного пользователя
 * @summary Текущий аккаунт
 */
const accountControllerMe = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AccountResponseDto>> => {
    return axiosInstance.get(
      `/account/me`,options
    );
  }

/**
 * Отправляет код подтверждения на новый email
 * @summary Инициация смены email
 */
const accountControllerInitEmail = (
    initEmailChangeRequestDto: InitEmailChangeRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ChangeResponseDto>> => {
    return axiosInstance.post(
      `/account/email/init`,
      initEmailChangeRequestDto,options
    );
  }

/**
 * Подтверждает email по коду
 * @summary Подтверждение смены email
 */
const accountControllerConfirmEmail = (
    confirmEmailChangeRequestDto: ConfirmEmailChangeRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ChangeResponseDto>> => {
    return axiosInstance.post(
      `/account/email/confirm`,
      confirmEmailChangeRequestDto,options
    );
  }

/**
 * Отправляет код подтверждения на новый номер телефона
 * @summary Инициация смены телефона
 */
const accountControllerInitPhone = (
    initPhoneChangeRequestDto: InitPhoneChangeRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ChangeResponseDto>> => {
    return axiosInstance.post(
      `/account/phone/init`,
      initPhoneChangeRequestDto,options
    );
  }

/**
 * Подтверждает номер телефона по коду
 * @summary Подтверждение смены телефона
 */
const accountControllerConfirmPhone = (
    confirmPhoneChangeRequestDto: ConfirmPhoneChangeRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ChangeResponseDto>> => {
    return axiosInstance.post(
      `/account/phone/confirm`,
      confirmPhoneChangeRequestDto,options
    );
  }

/**
 * Отправляет одноразовый 6-значный код на указанный номер телефона для входа.
 * @summary Отправка OTP-кода
 */
const authControllerSendOtp = (
    sendOtpRequest: SendOtpRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SendOtpResponseDto>> => {
    return axiosInstance.post(
      `/auth/otp/send`,
      sendOtpRequest,options
    );
  }

/**
 * Проверяет OTP-код, создает сессию и возвращает access token. Refresh token сохраняется в HttpOnly cookie.
 * @summary Подтверждение OTP-кода
 */
const authControllerVerify = (
    verifyOtpRequest: VerifyOtpRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AccessTokenResponseDto>> => {
    return axiosInstance.post(
      `/auth/otp/verify`,
      verifyOtpRequest,options
    );
  }

/**
 * Возвращает список активных сессий текущего пользователя. Поле `current=true` у текущего устройства.
 * @summary Получение активных сессий пользователя
 */
const authControllerList = (
    listSessionRequest: ListSessionRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ListSessionsResponseDto>> => {
    return axiosInstance.post(
      `/auth/list`,
      listSessionRequest,options
    );
  }

/**
 * Выпускает новый access token по refresh token из cookie и одновременно ротирует refresh token.
 * @summary Обновление access token
 */
const authControllerRefresh = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AccessTokenResponseDto>> => {
    return axiosInstance.post(
      `/auth/refresh`,undefined,options
    );
  }

/**
 * Завершает текущую сессию клиента: очищает refresh token из cookie.
 * @summary Выход из сессии
 */
const authControllerLogout = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OkResponseDto>> => {
    return axiosInstance.post(
      `/auth/logout`,undefined,options
    );
  }

/**
 * Завершает выбранную сессию по её `id`.
 * @summary Завершение конкретной сессии пользователя
 */
const authControllerRevokeSession = (
    revokeSessionRequestDto: RevokeSessionRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OkResponseDto>> => {
    return axiosInstance.post(
      `/auth/revoke`,
      revokeSessionRequestDto,options
    );
  }

/**
 * Возвращает профиль текущего авторизованного пользователя
 * @summary Текущий пользователь
 */
const usersControllerMe = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/users/me`,options
    );
  }

/**
 * Получает пользователя по id или username
 * @summary Получить пользователя
 */
const usersControllerGet = (
    getUserRequestDto: GetUserRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/users/get`,
      getUserRequestDto,options
    );
  }

/**
 * Создаёт пользователя в users-service по id
 * @summary Создать пользователя
 */
const usersControllerCreate = (
    createUserRequestDto: CreateUserRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/users/create`,
      createUserRequestDto,options
    );
  }

/**
 * Частично обновляет основные поля профиля пользователя
 * @summary Обновить профиль
 */
const usersControllerPatch = (
    patchUserRequestDto: PatchUserRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.patch(
      `/users`,
      patchUserRequestDto,options
    );
  }

/**
 * Частично обновляет настройки приватности текущего пользователя
 * @summary Обновить приватность
 */
const usersControllerPatchPrivacy = (
    patchPrivacyRequestDto: PatchPrivacyRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.patch(
      `/users/privacy`,
      patchPrivacyRequestDto,options
    );
  }

/**
 * Загружает новый аватар в media-service и добавляет его key в профиль
 * @summary Добавить аватар
 */
const usersControllerAddAvatar = (
    usersControllerAddAvatarBody: UsersControllerAddAvatarBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {const formData = new FormData();
formData.append(`file`, usersControllerAddAvatarBody.file);

    return axiosInstance.post(
      `/users/avatar`,
      formData,options
    );
  }

/**
 * Удаляет аватар из media-service и убирает его key из профиля
 * @summary Удалить аватар
 */
const usersControllerDeleteAvatar = (
    deleteAvatarRequestDto: DeleteAvatarRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/users/avatar`,{data:
      deleteAvatarRequestDto, ...options}
    );
  }

/**
 * Возвращает короткоживущий signed URL для приватного аватара
 * @summary Получить URL аватара
 */
const usersControllerGetAvatarUrl = (
    deleteAvatarRequestDto: DeleteAvatarRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/users/avatar/url`,
      deleteAvatarRequestDto,options
    );
  }

return {accountControllerMe,accountControllerInitEmail,accountControllerConfirmEmail,accountControllerInitPhone,accountControllerConfirmPhone,authControllerSendOtp,authControllerVerify,authControllerList,authControllerRefresh,authControllerLogout,authControllerRevokeSession,usersControllerMe,usersControllerGet,usersControllerCreate,usersControllerPatch,usersControllerPatchPrivacy,usersControllerAddAvatar,usersControllerDeleteAvatar,usersControllerGetAvatarUrl}};
export type AccountControllerMeResult = AxiosResponse<AccountResponseDto>
export type AccountControllerInitEmailResult = AxiosResponse<ChangeResponseDto>
export type AccountControllerConfirmEmailResult = AxiosResponse<ChangeResponseDto>
export type AccountControllerInitPhoneResult = AxiosResponse<ChangeResponseDto>
export type AccountControllerConfirmPhoneResult = AxiosResponse<ChangeResponseDto>
export type AuthControllerSendOtpResult = AxiosResponse<SendOtpResponseDto>
export type AuthControllerVerifyResult = AxiosResponse<AccessTokenResponseDto>
export type AuthControllerListResult = AxiosResponse<ListSessionsResponseDto>
export type AuthControllerRefreshResult = AxiosResponse<AccessTokenResponseDto>
export type AuthControllerLogoutResult = AxiosResponse<OkResponseDto>
export type AuthControllerRevokeSessionResult = AxiosResponse<OkResponseDto>
export type UsersControllerMeResult = AxiosResponse<void>
export type UsersControllerGetResult = AxiosResponse<void>
export type UsersControllerCreateResult = AxiosResponse<void>
export type UsersControllerPatchResult = AxiosResponse<void>
export type UsersControllerPatchPrivacyResult = AxiosResponse<void>
export type UsersControllerAddAvatarResult = AxiosResponse<void>
export type UsersControllerDeleteAvatarResult = AxiosResponse<void>
export type UsersControllerGetAvatarUrlResult = AxiosResponse<void>
