// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: media.proto

package mediav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Upload avatar request.
type UploadAvatarRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Auth/account id of the avatar owner.
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Original client file name.
	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// MIME type provided by client.
	ContentType string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Raw file bytes.
	Data          []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarRequest) Reset() {
	*x = UploadAvatarRequest{}
	mi := &file_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarRequest) ProtoMessage() {}

func (x *UploadAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarRequest.ProtoReflect.Descriptor instead.
func (*UploadAvatarRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

func (x *UploadAvatarRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UploadAvatarRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadAvatarRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadAvatarRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Uploaded avatar object metadata.
type AvatarObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Internal S3 object key.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Presigned GET URL.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// URL expiration time in epoch milliseconds.
	ExpiresAt     int64 `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarObject) Reset() {
	*x = AvatarObject{}
	mi := &file_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarObject) ProtoMessage() {}

func (x *AvatarObject) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarObject.ProtoReflect.Descriptor instead.
func (*AvatarObject) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{1}
}

func (x *AvatarObject) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AvatarObject) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AvatarObject) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// Upload avatar response.
type UploadAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Avatar        *AvatarObject          `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarResponse) Reset() {
	*x = UploadAvatarResponse{}
	mi := &file_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarResponse) ProtoMessage() {}

func (x *UploadAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarResponse.ProtoReflect.Descriptor instead.
func (*UploadAvatarResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{2}
}

func (x *UploadAvatarResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UploadAvatarResponse) GetAvatar() *AvatarObject {
	if x != nil {
		return x.Avatar
	}
	return nil
}

// Delete avatar request.
type DeleteAvatarRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Internal S3 object key.
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAvatarRequest) Reset() {
	*x = DeleteAvatarRequest{}
	mi := &file_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAvatarRequest) ProtoMessage() {}

func (x *DeleteAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAvatarRequest.ProtoReflect.Descriptor instead.
func (*DeleteAvatarRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteAvatarRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Delete avatar response.
type DeleteAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAvatarResponse) Reset() {
	*x = DeleteAvatarResponse{}
	mi := &file_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAvatarResponse) ProtoMessage() {}

func (x *DeleteAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAvatarResponse.ProtoReflect.Descriptor instead.
func (*DeleteAvatarResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAvatarResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Request signed URL for avatar.
type GetAvatarUrlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Internal S3 object key.
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvatarUrlRequest) Reset() {
	*x = GetAvatarUrlRequest{}
	mi := &file_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvatarUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvatarUrlRequest) ProtoMessage() {}

func (x *GetAvatarUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvatarUrlRequest.ProtoReflect.Descriptor instead.
func (*GetAvatarUrlRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{5}
}

func (x *GetAvatarUrlRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Signed URL response.
type GetAvatarUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Avatar        *AvatarObject          `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvatarUrlResponse) Reset() {
	*x = GetAvatarUrlResponse{}
	mi := &file_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvatarUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvatarUrlResponse) ProtoMessage() {}

func (x *GetAvatarUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvatarUrlResponse.ProtoReflect.Descriptor instead.
func (*GetAvatarUrlResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{6}
}

func (x *GetAvatarUrlResponse) GetAvatar() *AvatarObject {
	if x != nil {
		return x.Avatar
	}
	return nil
}

var File_media_proto protoreflect.FileDescriptor

const file_media_proto_rawDesc = "" +
	"\n" +
	"\vmedia.proto\x12\bmedia.v1\"\x88\x01\n" +
	"\x13UploadAvatarRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"Q\n" +
	"\fAvatarObject\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"V\n" +
	"\x14UploadAvatarResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12.\n" +
	"\x06avatar\x18\x02 \x01(\v2\x16.media.v1.AvatarObjectR\x06avatar\"'\n" +
	"\x13DeleteAvatarRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"&\n" +
	"\x14DeleteAvatarResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"'\n" +
	"\x13GetAvatarUrlRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"F\n" +
	"\x14GetAvatarUrlResponse\x12.\n" +
	"\x06avatar\x18\x01 \x01(\v2\x16.media.v1.AvatarObjectR\x06avatar2\xfb\x01\n" +
	"\fMediaService\x12M\n" +
	"\fUploadAvatar\x12\x1d.media.v1.UploadAvatarRequest\x1a\x1e.media.v1.UploadAvatarResponse\x12M\n" +
	"\fDeleteAvatar\x12\x1d.media.v1.DeleteAvatarRequest\x1a\x1e.media.v1.DeleteAvatarResponse\x12M\n" +
	"\fGetAvatarUrl\x12\x1d.media.v1.GetAvatarUrlRequest\x1a\x1e.media.v1.GetAvatarUrlResponseB#Z!media-service/internal/pb;mediav1b\x06proto3"

var (
	file_media_proto_rawDescOnce sync.Once
	file_media_proto_rawDescData []byte
)

func file_media_proto_rawDescGZIP() []byte {
	file_media_proto_rawDescOnce.Do(func() {
		file_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)))
	})
	return file_media_proto_rawDescData
}

var file_media_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_media_proto_goTypes = []any{
	(*UploadAvatarRequest)(nil),  // 0: media.v1.UploadAvatarRequest
	(*AvatarObject)(nil),         // 1: media.v1.AvatarObject
	(*UploadAvatarResponse)(nil), // 2: media.v1.UploadAvatarResponse
	(*DeleteAvatarRequest)(nil),  // 3: media.v1.DeleteAvatarRequest
	(*DeleteAvatarResponse)(nil), // 4: media.v1.DeleteAvatarResponse
	(*GetAvatarUrlRequest)(nil),  // 5: media.v1.GetAvatarUrlRequest
	(*GetAvatarUrlResponse)(nil), // 6: media.v1.GetAvatarUrlResponse
}
var file_media_proto_depIdxs = []int32{
	1, // 0: media.v1.UploadAvatarResponse.avatar:type_name -> media.v1.AvatarObject
	1, // 1: media.v1.GetAvatarUrlResponse.avatar:type_name -> media.v1.AvatarObject
	0, // 2: media.v1.MediaService.UploadAvatar:input_type -> media.v1.UploadAvatarRequest
	3, // 3: media.v1.MediaService.DeleteAvatar:input_type -> media.v1.DeleteAvatarRequest
	5, // 4: media.v1.MediaService.GetAvatarUrl:input_type -> media.v1.GetAvatarUrlRequest
	2, // 5: media.v1.MediaService.UploadAvatar:output_type -> media.v1.UploadAvatarResponse
	4, // 6: media.v1.MediaService.DeleteAvatar:output_type -> media.v1.DeleteAvatarResponse
	6, // 7: media.v1.MediaService.GetAvatarUrl:output_type -> media.v1.GetAvatarUrlResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_media_proto_init() }
func file_media_proto_init() {
	if File_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_proto_goTypes,
		DependencyIndexes: file_media_proto_depIdxs,
		MessageInfos:      file_media_proto_msgTypes,
	}.Build()
	File_media_proto = out.File
	file_media_proto_goTypes = nil
	file_media_proto_depIdxs = nil
}
